# Generated by Django 4.1.6 on 2024-11-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(max_length=64, verbose_name='小工具')),
                ('tools_desc', models.TextField(verbose_name='功能表述')),
                ('tools_freq', models.SmallIntegerField(verbose_name='使用频率')),
                ('tools_icon', models.ImageField(blank=True, upload_to='static/img/tools_icon')),
            ],
        ),
    ]
